version: '3'
services:
  app:
    image: node:6.10-slim
    working_dir: /usr/src
    ports:
      - "4567:4567"
    volumes:
        - ./src/app:/usr/src
        - ./src/nginx/srv/dist:/usr/src/static
        - ./dist:/usr/dist
        # Ensure node_modules cache doesn't clash with other jobs on CI.
        - /var/cache/tilejson.io-node-modules:/usr/src/node_modules
    command: yarn run test
